import {chromium} from 'playwright';
import assert from 'node:assert/strict';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath} from 'node:url';
import {resolve} from 'node:path';
const root=fileURLToPath(new URL('../',import.meta.url)),out=resolve(root,'qa');await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,...(process.env.CHROME_PATH?{executablePath:process.env.CHROME_PATH}:{})});
let checks=0;
const ok=(v,msg)=>{assert.ok(v,msg);checks++;console.log(`PASS ${msg}`);};
try{
 const ctx=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true,colorScheme:'light'}),page=await ctx.newPage(),req=[],errors=[];
 page.on('request',r=>{if(/^https?:/.test(r.url()))req.push(r.url());});page.on('pageerror',e=>errors.push(e.message));
 await page.goto(new URL('../dist/index.html',import.meta.url).href);
 ok(await page.locator('.candidate').count()===16,'file protocol demo');
 ok(await page.locator('.reasons li').count()===2,'all hard blockers');
 ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'desktop overflow');
 await page.screenshot({path:resolve(out,'desktop.png'),fullPage:true});
 await page.locator('#solve').click();await page.locator('.repair').first().waitFor();
 ok((await page.locator('.repair').first().textContent()).includes('2 changes'),'two-action repair');
 await page.screenshot({path:resolve(out,'solved.png'),fullPage:true});
 await page.locator('.apply').first().click();ok(await page.locator('#comparison').isVisible(),'comparison appears');
 ok((await page.locator('.reasons').textContent()).includes('Selected at'),'target admitted');
 await page.screenshot({path:resolve(out,'repaired.png'),fullPage:true});
 await page.locator('#undo').click();ok(await page.locator('.reasons li').count()===2,'undo restores blockers');
 await page.locator('#help').click();ok(await page.locator('#help-dialog').isVisible(),'help opens');
 await page.screenshot({path:resolve(out,'help.png')});await page.keyboard.press('Escape');ok(!await page.locator('#help-dialog').isVisible(),'Escape closes dialog');
 await page.locator('#export').click();ok((await page.locator('#export-note').textContent()).includes('sensitive'),'export data warning');
 const wait=page.waitForEvent('download');await page.locator('#download-scenario').click();const dl=await wait,saved=JSON.parse(await readFile(await dl.path(),'utf8'));
 ok(saved.items.length===16,'complete scenario download');
 const put=async(raw)=>page.locator('#file').setInputFiles({name:'scenario.json',mimeType:'application/json',buffer:Buffer.from(typeof raw==='string'?raw:JSON.stringify(raw))});
 await put(saved);await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Imported locally'));ok(await page.locator('.candidate').count()===16,'scenario roundtrip');
 await put('{broken');await page.waitForFunction(()=>document.querySelector('#notice').textContent.includes('Import rejected'));ok(await page.locator('.candidate').count()===16,'invalid import preserves data');
 const bad=structuredClone(saved);bad.items[0].title='<img src="https://example.invalid/leak" onerror="globalThis.pwned=1">';bad.items[0].author='</script><script>globalThis.pwned=1</script>';
 await put(bad);await page.waitForFunction(()=>document.querySelector('.item-title').textContent.includes('<img'));
 ok(await page.evaluate(()=>!globalThis.pwned&&!document.querySelector('#candidates img')),'injection is inert text');
 const precise=structuredClone(saved);precise.policy.weights.interest=.333;precise.policy.diversity=.127;
 await put(precise);await page.waitForFunction(()=>document.querySelector('#interest-value').textContent==='0.333');
 ok(await page.locator('#interest').inputValue()==='0.333'&&await page.locator('#diversity').inputValue()==='0.127','no snapping of imported precision');
 ok(await page.locator('#diversity-value').textContent()==='0.127','labels show actual policy');
 await page.evaluate(()=>{document.querySelector('#solve').click();const el=document.querySelector('#interest');el.value='.8';el.dispatchEvent(new Event('change',{bubbles:true}));});await page.waitForTimeout(100);
 ok(!await page.locator('#solve').isDisabled(),'edit cancels stale search');
 await page.locator('#solve').click();await page.locator('.search-summary').waitFor();ok(await page.locator('.search-summary').isVisible(),'new search works after cancellation');
 await page.locator('#reset').click();await page.locator('#search').fill('nonexistent item');ok(await page.locator('.empty').isVisible(),'empty search');await page.screenshot({path:resolve(out,'empty.png')});
 await page.locator('#reset').click();await ctx.setOffline(true);await page.locator('#solve').click();await page.locator('.repair').first().waitFor();ok(await page.locator('.repair').count()>0,'offline solving');
 await page.emulateMedia({colorScheme:'dark',reducedMotion:'reduce'});await page.screenshot({path:resolve(out,'dark.png'),fullPage:true});
 ok(req.length===0,'no outbound HTTP requests');ok(errors.length===0,'no browser exceptions');
 const mobile=await ctx.newPage();await mobile.setViewportSize({width:390,height:844});await mobile.emulateMedia({colorScheme:'light'});await mobile.goto(new URL('../dist/index.html',import.meta.url).href);
 ok(!await mobile.locator('#policy-details').getAttribute('open'),'mobile controls collapsed');
 ok(await mobile.evaluate(()=>document.documentElement.scrollWidth<=innerWidth),'mobile no horizontal overflow');
 await mobile.screenshot({path:resolve(out,'mobile.png'),fullPage:true});
 await mobile.locator('.policy-toggle').click();await mobile.locator('#maxAge').fill('60');await mobile.locator('#maxAge').press('Tab');ok(await mobile.locator('#maxAge').inputValue()==='60','mobile edit');
 await mobile.locator('.candidate').first().click();ok((await mobile.locator('#inspector h2').textContent()).includes('telescope'),'mobile candidate selection');
 await mobile.locator('#export').click();ok(await mobile.locator('#export-dialog').isVisible(),'mobile export dialog');await mobile.screenshot({path:resolve(out,'mobile-export.png')});
 console.log(`${checks} browser assertions passed.`);
}finally{await browser.close();}
